NAME_MAX_LENGTH = 150
EMAIL_MAX_LENGTH = 254

CHAR_FIELD_MAX_LENGTH = 256
SLUG_FIELD_MAX_LENGTH = 25

MIN_SCORE = 1
MAX_SCORE = 10
MIN_YEAR_PUB = -32768  # Нижняя граница SmallIntegerField

RESERVE_USERNAME = 'me'
